### ISSUE TITLE
ws 心跳优化

### ISSUE THREAD

**Issue by lesismal** [buexplain/netsvr#1]
感谢关注和使用nbio，我来个回访:smile:

简单扫了几眼，发现只有这里设置了读超时，后续message到来好像没有更新，这样的话到时间了应该会被判定读超时关闭：
https://github.com/buexplain/netsvr/blob/main/internal/customer/websocket.go#L208

通常是需要每次读到message后重新SetReadDeadline，而且由client主动发送心跳更优，避免服务端自己主动发包检测浪费

还可以设置 upgrader.KeepaliveTime，然后看框架读到message后会自动更新SetReadDeadline值：  
upgrade.KeepaliveTime = time.Duration(configs.Config.CustomerHeartbeatIntervalSecond) * time.Second

配合client主动发包，server就不需要这里的定时器检测功能了：
https://github.com/buexplain/netsvr/blob/main/internal/customer/websocket.go#L80

以上只是简单review得出的结论，实际情况以你跑的代码为准:smile:

**Comment by buexplain** [comment]
> 感谢关注和使用nbio，我来个回访😄
> 
> 简单扫了几眼，发现只有这里设置了读超时，后续message到来好像没有更新，这样的话到时间了应该会被判定读超时关闭： https://github.com/buexplain/netsvr/blob/main/internal/customer/websocket.go#L208
> 
> 通常是需要每次读到message后重新SetReadDeadline，而且由client主动发送心跳更优，避免服务端自己主动发包检测浪费
> 
> 还可以设置 upgrader.KeepaliveTime，然后看框架读到message后会自动更新SetReadDeadline值： upgrade.KeepaliveTime = time.Duration(configs.Config.CustomerHeartbeatIntervalSecond) * time.Second
> 
> 配合client主动发包，server就不需要这里的定时器检测功能了： https://github.com/buexplain/netsvr/blob/main/internal/customer/websocket.go#L80
> 
> 以上只是简单review得出的结论，实际情况以你跑的代码为准😄

感谢大佬指点，我改了一版代码。

**Comment by lesismal** [comment]
这速度，太效率了，哈哈哈，赞！
